version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER_POS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POS}
      POSTGRES_DB: ${DB_NAME_POS}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD_POS}@postgres:5432/${DB_NAME_POS}
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
